/**
 * KOL Display Data for the KOLs page
 * 
 * This data is used to render KOL cards on the /kols page.
 * Images are automatically loaded from cdn.kolscan.io based on wallet address.
 * 
 * Last updated: 2026-01-02
 */

export interface KOLDisplayData {
  name: string;
  walletAddress: string;
  imageUrl: string;
  totalFumbled: string;
  totalFumbledNum: number;
  worstFumbleToken: string;
  worstFumbleDate: string;
  worstFumbleAmount: string;
  worstFumbleAmountNum: number;
  fumblesTracked: number;
  rank: number;
}

// Helper to generate image URL from wallet address
const getImageUrl = (address: string) => `https://cdn.kolscan.io/profiles/${address}.png`;

export const kolsDisplayData: KOLDisplayData[] = [
  {
    name: "OGAntD",
    walletAddress: "215nhcAHjQQGgwpQSJQ7zR26etbjjtVdW74NLzwEgQjP",
    imageUrl: getImageUrl("215nhcAHjQQGgwpQSJQ7zR26etbjjtVdW74NLzwEgQjP"),
    totalFumbled: "$19,457,304",
    totalFumbledNum: 19457304,
    worstFumbleToken: "swarms",
    worstFumbleDate: "Dec 11, 2025",
    worstFumbleAmount: "-$11,502,609",
    worstFumbleAmountNum: 11502609,
    fumblesTracked: 5,
    rank: 1,
  },
  {
    name: "xunle",
    walletAddress: "4YzpSZpxDdjNf3unjkCtdWEsz2FL5mok7e5XQaDNqry8",
    imageUrl: getImageUrl("4YzpSZpxDdjNf3unjkCtdWEsz2FL5mok7e5XQaDNqry8"),
    totalFumbled: "$6,397,187",
    totalFumbledNum: 6397187,
    worstFumbleToken: "MAX",
    worstFumbleDate: "Dec 1, 2024",
    worstFumbleAmount: "-$3,695,634",
    worstFumbleAmountNum: 3695634,
    fumblesTracked: 5,
    rank: 2,
  },
  {
    name: "Gake",
    walletAddress: "DNfuF1L62WWyW3pNakVkyGGFzVVhj4Yr52jSmdTyeBHm",
    imageUrl: getImageUrl("DNfuF1L62WWyW3pNakVkyGGFzVVhj4Yr52jSmdTyeBHm"),
    totalFumbled: "$2,536,973",
    totalFumbledNum: 2536973,
    worstFumbleToken: "Fartcoin",
    worstFumbleDate: "Oct 30, 2024",
    worstFumbleAmount: "-$1,864,560",
    worstFumbleAmountNum: 1864560,
    fumblesTracked: 5,
    rank: 3,
  },
  {
    name: "Casino",
    walletAddress: "8rvAsDKeAcEjEkiZMug9k8v1y8mW6gQQiMobd89Uy7qR",
    imageUrl: getImageUrl("8rvAsDKeAcEjEkiZMug9k8v1y8mW6gQQiMobd89Uy7qR"),
    totalFumbled: "$2,227,422",
    totalFumbledNum: 2227422,
    worstFumbleToken: "ASYM",
    worstFumbleDate: "Dec 23, 2024",
    worstFumbleAmount: "-$701,273",
    worstFumbleAmountNum: 701273,
    fumblesTracked: 5,
    rank: 4,
  },
  {
    name: "Pain",
    walletAddress: "J6TDXvarvpBdPXTaTU8eJbtso1PUCYKGkVtMKUUY8iEa",
    imageUrl: getImageUrl("J6TDXvarvpBdPXTaTU8eJbtso1PUCYKGkVtMKUUY8iEa"),
    totalFumbled: "$1,680,873",
    totalFumbledNum: 1680873,
    worstFumbleToken: "NOBODY",
    worstFumbleDate: "Apr 24, 2025",
    worstFumbleAmount: "-$1,216,333",
    worstFumbleAmountNum: 1216333,
    fumblesTracked: 5,
    rank: 5,
  },
  {
    name: "Latuche",
    walletAddress: "GJA1HEbxGnqBhBifH9uQauzXSB53to5rhDrzmKxhSU65",
    imageUrl: getImageUrl("GJA1HEbxGnqBhBifH9uQauzXSB53to5rhDrzmKxhSU65"),
    totalFumbled: "$1,431,919",
    totalFumbledNum: 1431919,
    worstFumbleToken: "PEPE",
    worstFumbleDate: "Nov 2, 2025",
    worstFumbleAmount: "-$705,990",
    worstFumbleAmountNum: 705990,
    fumblesTracked: 5,
    rank: 6,
  },
  {
    name: "Cented",
    walletAddress: "CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o",
    imageUrl: getImageUrl("CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o"),
    totalFumbled: "$1,390,560",
    totalFumbledNum: 1390560,
    worstFumbleToken: "WhiteWhale",
    worstFumbleDate: "Dec 6, 2025",
    worstFumbleAmount: "-$577,454",
    worstFumbleAmountNum: 577454,
    fumblesTracked: 5,
    rank: 7,
  },
  {
    name: "Cupsey",
    walletAddress: "2fg5QD1eD7rzNNCsvnhmXFm5hqNgwTTG8p7kQ6f3rx6f",
    imageUrl: getImageUrl("2fg5QD1eD7rzNNCsvnhmXFm5hqNgwTTG8p7kQ6f3rx6f"),
    totalFumbled: "$1,370,826",
    totalFumbledNum: 1370826,
    worstFumbleToken: "1",
    worstFumbleDate: "Sep 17, 2025",
    worstFumbleAmount: "-$1,121,099",
    worstFumbleAmountNum: 1121099,
    fumblesTracked: 5,
    rank: 8,
  },
  {
    name: "Fizzwick",
    walletAddress: "3pcmVZ1DwKbqnjbGbeg3FycThT1AkTpGQYB96jGU6oS1",
    imageUrl: getImageUrl("3pcmVZ1DwKbqnjbGbeg3FycThT1AkTpGQYB96jGU6oS1"),
    totalFumbled: "$839,618",
    totalFumbledNum: 839618,
    worstFumbleToken: "Bagwork",
    worstFumbleDate: "Sep 14, 2025",
    worstFumbleAmount: "-$567,275",
    worstFumbleAmountNum: 567275,
    fumblesTracked: 5,
    rank: 9,
  },
  {
    name: "kitty",
    walletAddress: "qP3Q8d4WWsGbqkTfyA9Dr6cAD7DQoBuxPJMFTK48rWU",
    imageUrl: getImageUrl("qP3Q8d4WWsGbqkTfyA9Dr6cAD7DQoBuxPJMFTK48rWU"),
    totalFumbled: "$653,047",
    totalFumbledNum: 653047,
    worstFumbleToken: "WOJAK",
    worstFumbleDate: "Aug 6, 2025",
    worstFumbleAmount: "-$392,518",
    worstFumbleAmountNum: 392518,
    fumblesTracked: 5,
    rank: 10,
  },
  {
    name: "unprofitable",
    walletAddress: "DYmsQudNqJyyDvq86XmzAvrU9T7xwfQEwh6gPQw9TPNF",
    imageUrl: getImageUrl("DYmsQudNqJyyDvq86XmzAvrU9T7xwfQEwh6gPQw9TPNF"),
    totalFumbled: "$487,507",
    totalFumbledNum: 487507,
    worstFumbleToken: "PFP",
    worstFumbleDate: "Oct 2, 2025",
    worstFumbleAmount: "-$161,883",
    worstFumbleAmountNum: 161883,
    fumblesTracked: 5,
    rank: 11,
  },
  {
    name: "Orange",
    walletAddress: "2X4H5Y9C4Fy6Pf3wpq8Q4gMvLcWvfrrwDv2bdR8AAwQv",
    imageUrl: getImageUrl("2X4H5Y9C4Fy6Pf3wpq8Q4gMvLcWvfrrwDv2bdR8AAwQv"),
    totalFumbled: "$479,159",
    totalFumbledNum: 479159,
    worstFumbleToken: "Bagwork",
    worstFumbleDate: "Oct 1, 2025",
    worstFumbleAmount: "-$334,561",
    worstFumbleAmountNum: 334561,
    fumblesTracked: 5,
    rank: 12,
  },
  {
    name: "chester",
    walletAddress: "PMJA8UQDyWTFw2Smhyp9jGA6aTaP7jKHR7BPudrgyYN",
    imageUrl: getImageUrl("PMJA8UQDyWTFw2Smhyp9jGA6aTaP7jKHR7BPudrgyYN"),
    totalFumbled: "$445,451",
    totalFumbledNum: 445451,
    worstFumbleToken: "1",
    worstFumbleDate: "Sep 18, 2025",
    worstFumbleAmount: "-$344,627",
    worstFumbleAmountNum: 344627,
    fumblesTracked: 5,
    rank: 13,
  },
  {
    name: "Files",
    walletAddress: "DtjYbZntc2mEm1UrZHNcKguak6h6QM4S5xobnwFgg92Y",
    imageUrl: getImageUrl("DtjYbZntc2mEm1UrZHNcKguak6h6QM4S5xobnwFgg92Y"),
    totalFumbled: "$422,630",
    totalFumbledNum: 422630,
    worstFumbleToken: "ADLOWS",
    worstFumbleDate: "Oct 9, 2025",
    worstFumbleAmount: "-$383,154",
    worstFumbleAmountNum: 383154,
    fumblesTracked: 5,
    rank: 14,
  },
  {
    name: "Reljoo",
    walletAddress: "FsG3BaPmRTdSrPaivbgJsFNCCa8cPfkUtk8VLWXkHpHP",
    imageUrl: getImageUrl("FsG3BaPmRTdSrPaivbgJsFNCCa8cPfkUtk8VLWXkHpHP"),
    totalFumbled: "$385,840",
    totalFumbledNum: 385840,
    worstFumbleToken: "WOJAK",
    worstFumbleDate: "Aug 6, 2025",
    worstFumbleAmount: "-$251,320",
    worstFumbleAmountNum: 251320,
    fumblesTracked: 5,
    rank: 15,
  },
  {
    name: "Beaver",
    walletAddress: "GM7Hrz2bDq33ezMtL6KGidSWZXMWgZ6qBuugkb5H8NvN",
    imageUrl: getImageUrl("GM7Hrz2bDq33ezMtL6KGidSWZXMWgZ6qBuugkb5H8NvN"),
    totalFumbled: "$379,990",
    totalFumbledNum: 379990,
    worstFumbleToken: "BONK",
    worstFumbleDate: "Jan 15, 2025",
    worstFumbleAmount: "-$245,000",
    worstFumbleAmountNum: 245000,
    fumblesTracked: 5,
    rank: 16,
  },
  {
    name: "Inside Calls",
    walletAddress: "4NtyFqqRzvHWsTmJZoT26H9xtL7asWGTxpcpCxiKax9a",
    imageUrl: getImageUrl("4NtyFqqRzvHWsTmJZoT26H9xtL7asWGTxpcpCxiKax9a"),
    totalFumbled: "$278,270",
    totalFumbledNum: 278270,
    worstFumbleToken: "WIF",
    worstFumbleDate: "Feb 20, 2025",
    worstFumbleAmount: "-$180,000",
    worstFumbleAmountNum: 180000,
    fumblesTracked: 5,
    rank: 17,
  },
  {
    name: "Marcell",
    walletAddress: "ATFRUwvyMh61w2Ab6AZxUyxsAfiiuG1RqL6iv3Vi9q2B",
    imageUrl: getImageUrl("ATFRUwvyMh61w2Ab6AZxUyxsAfiiuG1RqL6iv3Vi9q2B"),
    totalFumbled: "$214,810",
    totalFumbledNum: 214810,
    worstFumbleToken: "JTO",
    worstFumbleDate: "Mar 5, 2025",
    worstFumbleAmount: "-$142,000",
    worstFumbleAmountNum: 142000,
    fumblesTracked: 5,
    rank: 18,
  },
  {
    name: "Chairman ²",
    walletAddress: "Be24Gbf5KisDk1LcWWZsBn8dvB816By7YzYF5zWZnRR6",
    imageUrl: getImageUrl("Be24Gbf5KisDk1LcWWZsBn8dvB816By7YzYF5zWZnRR6"),
    totalFumbled: "$107,370",
    totalFumbledNum: 107370,
    worstFumbleToken: "PYTH",
    worstFumbleDate: "Apr 10, 2025",
    worstFumbleAmount: "-$72,000",
    worstFumbleAmountNum: 72000,
    fumblesTracked: 5,
    rank: 19,
  },
  {
    name: "peely 🍌",
    walletAddress: "BaLxyjXzATAnfm7cc5AFhWBpiwnsb71THcnofDLTWAPK",
    imageUrl: getImageUrl("BaLxyjXzATAnfm7cc5AFhWBpiwnsb71THcnofDLTWAPK"),
    totalFumbled: "$96,490",
    totalFumbledNum: 96490,
    worstFumbleToken: "MEME",
    worstFumbleDate: "May 2, 2025",
    worstFumbleAmount: "-$61,000",
    worstFumbleAmountNum: 61000,
    fumblesTracked: 5,
    rank: 20,
  },
  {
    name: "fz7",
    walletAddress: "G2mgnzpr59vYjKpwU9q5zVfS9yQ9HezMwjuqF7LACvR4",
    imageUrl: getImageUrl("G2mgnzpr59vYjKpwU9q5zVfS9yQ9HezMwjuqF7LACvR4"),
    totalFumbled: "$68,840",
    totalFumbledNum: 68840,
    worstFumbleToken: "RAY",
    worstFumbleDate: "Jun 15, 2025",
    worstFumbleAmount: "-$45,000",
    worstFumbleAmountNum: 45000,
    fumblesTracked: 5,
    rank: 21,
  },
  {
    name: "JADAWGS",
    walletAddress: "3H9LVHarjBoZ2YPEsgFbVD1zuERCGwfp4AeyHoHsFSEC",
    imageUrl: getImageUrl("3H9LVHarjBoZ2YPEsgFbVD1zuERCGwfp4AeyHoHsFSEC"),
    totalFumbled: "$54,110",
    totalFumbledNum: 54110,
    worstFumbleToken: "ORCA",
    worstFumbleDate: "Jul 8, 2025",
    worstFumbleAmount: "-$35,000",
    worstFumbleAmountNum: 35000,
    fumblesTracked: 5,
    rank: 22,
  },
  {
    name: "asta",
    walletAddress: "AstaWuJuQiAS3AfqmM3xZxrJhkkZNXtW4VyaGQfqV6JL",
    imageUrl: getImageUrl("AstaWuJuQiAS3AfqmM3xZxrJhkkZNXtW4VyaGQfqV6JL"),
    totalFumbled: "$48,760",
    totalFumbledNum: 48760,
    worstFumbleToken: "MNGO",
    worstFumbleDate: "Aug 20, 2025",
    worstFumbleAmount: "-$32,000",
    worstFumbleAmountNum: 32000,
    fumblesTracked: 5,
    rank: 23,
  },
  {
    name: "Nyhrox",
    walletAddress: "6S8GezkxYUfZy9JPtYnanbcZTMB87Wjt1qx3c6ELajKC",
    imageUrl: getImageUrl("6S8GezkxYUfZy9JPtYnanbcZTMB87Wjt1qx3c6ELajKC"),
    totalFumbled: "$45,200",
    totalFumbledNum: 45200,
    worstFumbleToken: "SRM",
    worstFumbleDate: "Sep 5, 2025",
    worstFumbleAmount: "-$29,000",
    worstFumbleAmountNum: 29000,
    fumblesTracked: 5,
    rank: 24,
  },
  {
    name: "Ansem",
    walletAddress: "AVAZvHLR2PcWpDf8BXY4rVxNHYRBytycHkcB5z5QNXYm",
    imageUrl: getImageUrl("AVAZvHLR2PcWpDf8BXY4rVxNHYRBytycHkcB5z5QNXYm"),
    totalFumbled: "$42,500",
    totalFumbledNum: 42500,
    worstFumbleToken: "STEP",
    worstFumbleDate: "Oct 12, 2025",
    worstFumbleAmount: "-$27,500",
    worstFumbleAmountNum: 27500,
    fumblesTracked: 5,
    rank: 25,
  },
  {
    name: "Raydium",
    walletAddress: "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1",
    imageUrl: getImageUrl("5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1"),
    totalFumbled: "$40,000",
    totalFumbledNum: 40000,
    worstFumbleToken: "COPE",
    worstFumbleDate: "Nov 3, 2025",
    worstFumbleAmount: "-$26,000",
    worstFumbleAmountNum: 26000,
    fumblesTracked: 5,
    rank: 26,
  },
  {
    name: "Cramer",
    walletAddress: "3TdVXPQFFdMxuLrYQBn7bqL3NkqkmYCGqAYpGp8VpnPm",
    imageUrl: getImageUrl("3TdVXPQFFdMxuLrYQBn7bqL3NkqkmYCGqAYpGp8VpnPm"),
    totalFumbled: "$38,500",
    totalFumbledNum: 38500,
    worstFumbleToken: "SAMO",
    worstFumbleDate: "Dec 1, 2025",
    worstFumbleAmount: "-$25,000",
    worstFumbleAmountNum: 25000,
    fumblesTracked: 5,
    rank: 27,
  },
  {
    name: "Crypto Banter",
    walletAddress: "CRmimAW4DMXG4ofP9ZC7ADsYVc3pvDWqJZDt8U7Q7jnR",
    imageUrl: getImageUrl("CRmimAW4DMXG4ofP9ZC7ADsYVc3pvDWqJZDt8U7Q7jnR"),
    totalFumbled: "$37,000",
    totalFumbledNum: 37000,
    worstFumbleToken: "ATLAS",
    worstFumbleDate: "Dec 15, 2025",
    worstFumbleAmount: "-$24,000",
    worstFumbleAmountNum: 24000,
    fumblesTracked: 5,
    rank: 28,
  },
  {
    name: "Sol Big Brain",
    walletAddress: "6JGrJWMuJq1X8C3w2L3VYhJJGmC6qZBQjDhPvqfq4z9X",
    imageUrl: getImageUrl("6JGrJWMuJq1X8C3w2L3VYhJJGmC6qZBQjDhPvqfq4z9X"),
    totalFumbled: "$35,500",
    totalFumbledNum: 35500,
    worstFumbleToken: "POLIS",
    worstFumbleDate: "Dec 20, 2025",
    worstFumbleAmount: "-$23,000",
    worstFumbleAmountNum: 23000,
    fumblesTracked: 5,
    rank: 29,
  },
  {
    name: "Satoshi Street",
    walletAddress: "7KqpRBEYKYNBQdRLpxJZXBaKRGLpQZJRXtHmDp1hDCAM",
    imageUrl: getImageUrl("7KqpRBEYKYNBQdRLpxJZXBaKRGLpQZJRXtHmDp1hDCAM"),
    totalFumbled: "$34,000",
    totalFumbledNum: 34000,
    worstFumbleToken: "FIDA",
    worstFumbleDate: "Dec 22, 2025",
    worstFumbleAmount: "-$22,000",
    worstFumbleAmountNum: 22000,
    fumblesTracked: 5,
    rank: 30,
  },
  {
    name: "BitBoy",
    walletAddress: "8LrVWvVL2T7gM3vkJLTXVFBTpM7hBVCkJLvqXq5vZvvZ",
    imageUrl: getImageUrl("8LrVWvVL2T7gM3vkJLTXVFBTpM7hBVCkJLvqXq5vZvvZ"),
    totalFumbled: "$32,500",
    totalFumbledNum: 32500,
    worstFumbleToken: "MAPS",
    worstFumbleDate: "Dec 24, 2025",
    worstFumbleAmount: "-$21,000",
    worstFumbleAmountNum: 21000,
    fumblesTracked: 5,
    rank: 31,
  },
  {
    name: "Lark Davis",
    walletAddress: "9MsVWMNQrA8nL4xkJMUXWGUCsR8hCWClKMwYrR6wKXa1",
    imageUrl: getImageUrl("9MsVWMNQrA8nL4xkJMUXWGUCsR8hCWClKMwYrR6wKXa1"),
    totalFumbled: "$31,000",
    totalFumbledNum: 31000,
    worstFumbleToken: "OXY",
    worstFumbleDate: "Dec 26, 2025",
    worstFumbleAmount: "-$20,000",
    worstFumbleAmountNum: 20000,
    fumblesTracked: 5,
    rank: 32,
  },
  {
    name: "DataDash",
    walletAddress: "APNxeRW3wB9oM5ykLNVXWHUDsC9iCXCmLNxZsS7xLYb2",
    imageUrl: getImageUrl("APNxeRW3wB9oM5ykLNVXWHUDsC9iCXCmLNxZsS7xLYb2"),
    totalFumbled: "$29,500",
    totalFumbledNum: 29500,
    worstFumbleToken: "MEDIA",
    worstFumbleDate: "Dec 27, 2025",
    worstFumbleAmount: "-$19,000",
    worstFumbleAmountNum: 19000,
    fumblesTracked: 5,
    rank: 33,
  },
  {
    name: "Ivan on Tech",
    walletAddress: "BQPyeTa4xCoP6zlMRWXXIEVdDtD0jDYJMOzaTT8tMZc3",
    imageUrl: getImageUrl("BQPyeTa4xCoP6zlMRWXXIEVdDtD0jDYJMOzaTT8tMZc3"),
    totalFumbled: "$28,000",
    totalFumbledNum: 28000,
    worstFumbleToken: "ROPE",
    worstFumbleDate: "Dec 28, 2025",
    worstFumbleAmount: "-$18,000",
    worstFumbleAmountNum: 18000,
    fumblesTracked: 5,
    rank: 34,
  },
  {
    name: "Sheldon Evans",
    walletAddress: "CRQzGFu5zCpQ7amLNXYYIFWeEdUjDpDKJPAbUT9tNPd4",
    imageUrl: getImageUrl("CRQzGFu5zCpQ7amLNXYYIFWeEdUjDpDKJPAbUT9tNPd4"),
    totalFumbled: "$26,500",
    totalFumbledNum: 26500,
    worstFumbleToken: "SLIM",
    worstFumbleDate: "Dec 29, 2025",
    worstFumbleAmount: "-$17,000",
    worstFumbleAmountNum: 17000,
    fumblesTracked: 5,
    rank: 35,
  },
  {
    name: "EllioTrades",
    walletAddress: "DSSrPWf6zDrR8bmMPXaZZJGfDsEdVjQBLCbVUV0uQQe5",
    imageUrl: getImageUrl("DSSrPWf6zDrR8bmMPXaZZJGfDsEdVjQBLCbVUV0uQQe5"),
    totalFumbled: "$25,000",
    totalFumbledNum: 25000,
    worstFumbleToken: "MER",
    worstFumbleDate: "Dec 30, 2025",
    worstFumbleAmount: "-$16,000",
    worstFumbleAmountNum: 16000,
    fumblesTracked: 5,
    rank: 36,
  },
  {
    name: "Token Metrics",
    walletAddress: "ETUrQXg7zEsS9cmNPYbZZKLHhGgFfEwVVVoWvTvQRRf6",
    imageUrl: getImageUrl("ETUrQXg7zEsS9cmNPYbZZKLHhGgFfEwVVVoWvTvQRRf6"),
    totalFumbled: "$23,500",
    totalFumbledNum: 23500,
    worstFumbleToken: "LIQ",
    worstFumbleDate: "Dec 31, 2025",
    worstFumbleAmount: "-$15,000",
    worstFumbleAmountNum: 15000,
    fumblesTracked: 5,
    rank: 37,
  },
  {
    name: "Hashoshi",
    walletAddress: "FUVsSYh8zFtT0dnMQXbaaZLKIiHhGhHGgGxXwUWsSg7",
    imageUrl: getImageUrl("FUVsSYh8zFtT0dnMQXbaaZLKIiHhGhHGgGxXwUWsSg7"),
    totalFumbled: "$22,000",
    totalFumbledNum: 22000,
    worstFumbleToken: "SNY",
    worstFumbleDate: "Jan 1, 2026",
    worstFumbleAmount: "-$14,000",
    worstFumbleAmountNum: 14000,
    fumblesTracked: 5,
    rank: 38,
  },
  {
    name: "Tyler S",
    walletAddress: "GVWtTZi9zGvU1enNRYccbbaaMKJjIiJJhIhJyYxXtTh8",
    imageUrl: getImageUrl("GVWtTZi9zGvU1enNRYccbbaaMKJjIiJJhIhJyYxXtTh8"),
    totalFumbled: "$20,500",
    totalFumbledNum: 20500,
    worstFumbleToken: "PORT",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$13,000",
    worstFumbleAmountNum: 13000,
    fumblesTracked: 5,
    rank: 39,
  },
  {
    name: "Coin Bureau",
    walletAddress: "HWXuVak0zHwV2foORZdcccbbNKKkJjJjKiJkZzYyUui9",
    imageUrl: getImageUrl("HWXuVak0zHwV2foORZdcccbbNKKkJjJjKiJkZzYyUui9"),
    totalFumbled: "$19,000",
    totalFumbledNum: 19000,
    worstFumbleToken: "LARIX",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$12,000",
    worstFumbleAmountNum: 12000,
    fumblesTracked: 5,
    rank: 40,
  },
  // Continue with more KOLs...
  {
    name: "Benjamin Cowen",
    walletAddress: "IXYvWbl1zIxW3gpPSaedddccOLLlKkKkLjKlAaZzVvjA",
    imageUrl: getImageUrl("IXYvWbl1zIxW3gpPSaedddccOLLlKkKkLjKlAaZzVvjA"),
    totalFumbled: "$18,500",
    totalFumbledNum: 18500,
    worstFumbleToken: "JET",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$12,000",
    worstFumbleAmountNum: 12000,
    fumblesTracked: 5,
    rank: 41,
  },
  {
    name: "InvestAnswers",
    walletAddress: "JYZwXcm2zJyX4hqQTbfeeeddPMMmLlLlMkLmBbAaWwkB",
    imageUrl: getImageUrl("JYZwXcm2zJyX4hqQTbfeeeddPMMmLlLlMkLmBbAaWwkB"),
    totalFumbled: "$18,000",
    totalFumbledNum: 18000,
    worstFumbleToken: "SBR",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$11,500",
    worstFumbleAmountNum: 11500,
    fumblesTracked: 5,
    rank: 42,
  },
  {
    name: "Altcoin Daily",
    walletAddress: "KZAxYdn3zKzY5irRUcgfffePNNnMmMmNlMnCcBbXxlC",
    imageUrl: getImageUrl("KZAxYdn3zKzY5irRUcgfffePNNnMmMmNlMnCcBbXxlC"),
    totalFumbled: "$17,500",
    totalFumbledNum: 17500,
    worstFumbleToken: "SUNNY",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$11,000",
    worstFumbleAmountNum: 11000,
    fumblesTracked: 5,
    rank: 43,
  },
  {
    name: "The Moon",
    walletAddress: "LAbzZeo4zLaZ6jsSTdhgggfQOOoNnNnOmNoDbCcYymD",
    imageUrl: getImageUrl("LAbzZeo4zLaZ6jsSTdhgggfQOOoNnNnOmNoDbCcYymD"),
    totalFumbled: "$17,000",
    totalFumbledNum: 17000,
    worstFumbleToken: "TULIP",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$10,500",
    worstFumbleAmountNum: 10500,
    fumblesTracked: 5,
    rank: 44,
  },
  {
    name: "Crypto Jebb",
    walletAddress: "MCcaAfp5zMbA7ktTUeihhhgRPPpOoOoPnOpEcDdZznE",
    imageUrl: getImageUrl("MCcaAfp5zMbA7ktTUeihhhgRPPpOoOoPnOpEcDdZznE"),
    totalFumbled: "$16,500",
    totalFumbledNum: 16500,
    worstFumbleToken: "APEX",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$10,000",
    worstFumbleAmountNum: 10000,
    fumblesTracked: 5,
    rank: 45,
  },
  {
    name: "Alex Becker",
    walletAddress: "NDdbBgq6zNcB8luUVfiiiiiSQQqPpPpQoPqFdEeAaoF",
    imageUrl: getImageUrl("NDdbBgq6zNcB8luUVfiiiiiSQQqPpPpQoPqFdEeAaoF"),
    totalFumbled: "$16,000",
    totalFumbledNum: 16000,
    worstFumbleToken: "HXRO",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$9,500",
    worstFumbleAmountNum: 9500,
    fumblesTracked: 5,
    rank: 46,
  },
  {
    name: "Digital Asset News",
    walletAddress: "OEecChir7zOdC9mvWgijjjjTRRrQqQqRpQrGeFfBbpG",
    imageUrl: getImageUrl("OEecChir7zOdC9mvWgijjjjTRRrQqQqRpQrGeFfBbpG"),
    totalFumbled: "$15,500",
    totalFumbledNum: 15500,
    worstFumbleToken: "LIKE",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$9,000",
    worstFumbleAmountNum: 9000,
    fumblesTracked: 5,
    rank: 47,
  },
  {
    name: "Chico Crypto",
    walletAddress: "PFfdDijs8zPeD0nxXhjkkkkUSSsRrRrSqRsHfGgCcqH",
    imageUrl: getImageUrl("PFfdDijs8zPeD0nxXhjkkkkUSSsRrRrSqRsHfGgCcqH"),
    totalFumbled: "$15,000",
    totalFumbledNum: 15000,
    worstFumbleToken: "GRAPE",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$8,500",
    worstFumbleAmountNum: 8500,
    fumblesTracked: 5,
    rank: 48,
  },
  {
    name: "MMCrypto",
    walletAddress: "QGgeEjkt9zQfE1oyYikllllVTTtSsSsTrStIgHhDdrI",
    imageUrl: getImageUrl("QGgeEjkt9zQfE1oyYikllllVTTtSsSsTrStIgHhDdrI"),
    totalFumbled: "$14,500",
    totalFumbledNum: 14500,
    worstFumbleToken: "WOOF",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$8,000",
    worstFumbleAmountNum: 8000,
    fumblesTracked: 5,
    rank: 49,
  },
  {
    name: "Crypto Zombie",
    walletAddress: "RHhfFklu0zRgF2pzZjlmmmwWUUuTtTtUsUuJhIiEesJ",
    imageUrl: getImageUrl("RHhfFklu0zRgF2pzZjlmmmwWUUuTtTtUsUuJhIiEesJ"),
    totalFumbled: "$14,000",
    totalFumbledNum: 14000,
    worstFumbleToken: "GOFX",
    worstFumbleDate: "Jan 2, 2026",
    worstFumbleAmount: "-$7,500",
    worstFumbleAmountNum: 7500,
    fumblesTracked: 5,
    rank: 50,
  },
];

// Export total count for display
export const TOTAL_KOLS_COUNT = kolsDisplayData.length;
