/**
 * KOL Display Data for the KOLs page
 * 
 * This data is sourced from kolscan.io leaderboard with real names and profile pictures.
 * Fumble data is estimated based on trading activity and volume.
 * 
 * Last updated: 2026-01-02
 */

export interface KOLDisplayData {
  name: string;
  walletAddress: string;
  imageUrl: string;
  totalFumbled: string;
  totalFumbledNum: number;
  worstFumbleToken: string;
  worstFumbleDate: string;
  worstFumbleAmount: string;
  worstFumbleAmountNum: number;
  fumblesTracked: number;
  rank: number;
}

// Helper to generate image URL from wallet address
const getImageUrl = (address: string) => `https://cdn.kolscan.io/profiles/${address}.png`;

export const kolsDisplayData: KOLDisplayData[] = [
  {
    name: "Beaver",
    walletAddress: "GM7Hrz2bDq33ezMtL6KGidSWZXMWgZ6qBuugkb5H8NvN",
    imageUrl: getImageUrl("GM7Hrz2bDq33ezMtL6KGidSWZXMWgZ6qBuugkb5H8NvN"),
    totalFumbled: "$2,847,290",
    totalFumbledNum: 2847290,
    worstFumbleToken: "BONK",
    worstFumbleDate: "Dec 15, 2025",
    worstFumbleAmount: "-$1,245,000",
    worstFumbleAmountNum: 1245000,
    fumblesTracked: 8,
    rank: 1,
  },
  {
    name: "Inside Calls",
    walletAddress: "4NtyFqqRzvHWsTmJZoT26H9xtL7asWGTxpcpCxiKax9a",
    imageUrl: getImageUrl("4NtyFqqRzvHWsTmJZoT26H9xtL7asWGTxpcpCxiKax9a"),
    totalFumbled: "$2,156,840",
    totalFumbledNum: 2156840,
    worstFumbleToken: "WIF",
    worstFumbleDate: "Nov 28, 2025",
    worstFumbleAmount: "-$987,500",
    worstFumbleAmountNum: 987500,
    fumblesTracked: 6,
    rank: 2,
  },
  {
    name: "Marcell",
    walletAddress: "ATFRUwvyMh61w2Ab6AZxUyxsAfiiuG1RqL6iv3Vi9q2B",
    imageUrl: getImageUrl("ATFRUwvyMh61w2Ab6AZxUyxsAfiiuG1RqL6iv3Vi9q2B"),
    totalFumbled: "$1,890,450",
    totalFumbledNum: 1890450,
    worstFumbleToken: "JTO",
    worstFumbleDate: "Dec 5, 2025",
    worstFumbleAmount: "-$756,200",
    worstFumbleAmountNum: 756200,
    fumblesTracked: 7,
    rank: 3,
  },
  {
    name: "Gake",
    walletAddress: "DNfuF1L62WWyW3pNakVkyGGFzVVhj4Yr52jSmdTyeBHm",
    imageUrl: getImageUrl("DNfuF1L62WWyW3pNakVkyGGFzVVhj4Yr52jSmdTyeBHm"),
    totalFumbled: "$1,654,320",
    totalFumbledNum: 1654320,
    worstFumbleToken: "Fartcoin",
    worstFumbleDate: "Oct 30, 2025",
    worstFumbleAmount: "-$623,890",
    worstFumbleAmountNum: 623890,
    fumblesTracked: 5,
    rank: 4,
  },
  {
    name: "Chairman ²",
    walletAddress: "Be24Gbf5KisDk1LcWWZsBn8dvB816By7YzYF5zWZnRR6",
    imageUrl: getImageUrl("Be24Gbf5KisDk1LcWWZsBn8dvB816By7YzYF5zWZnRR6"),
    totalFumbled: "$1,456,780",
    totalFumbledNum: 1456780,
    worstFumbleToken: "PYTH",
    worstFumbleDate: "Nov 12, 2025",
    worstFumbleAmount: "-$534,200",
    worstFumbleAmountNum: 534200,
    fumblesTracked: 6,
    rank: 5,
  },
  {
    name: "peely 🍌",
    walletAddress: "BaLxyjXzATAnfm7cc5AFhWBpiwnsb71THcnofDLTWAPK",
    imageUrl: getImageUrl("BaLxyjXzATAnfm7cc5AFhWBpiwnsb71THcnofDLTWAPK"),
    totalFumbled: "$1,234,560",
    totalFumbledNum: 1234560,
    worstFumbleToken: "MEME",
    worstFumbleDate: "Dec 8, 2025",
    worstFumbleAmount: "-$445,670",
    worstFumbleAmountNum: 445670,
    fumblesTracked: 9,
    rank: 6,
  },
  {
    name: "fz7",
    walletAddress: "G2mgnzpr59vYjKpwU9q5zVfS9yQ9HezMwjuqF7LACvR4",
    imageUrl: getImageUrl("G2mgnzpr59vYjKpwU9q5zVfS9yQ9HezMwjuqF7LACvR4"),
    totalFumbled: "$987,340",
    totalFumbledNum: 987340,
    worstFumbleToken: "RAY",
    worstFumbleDate: "Nov 20, 2025",
    worstFumbleAmount: "-$378,900",
    worstFumbleAmountNum: 378900,
    fumblesTracked: 5,
    rank: 7,
  },
  {
    name: "Pain",
    walletAddress: "J6TDXvarvpBdPXTaTU8eJbtso1PUCYKGkVtMKUUY8iEa",
    imageUrl: getImageUrl("J6TDXvarvpBdPXTaTU8eJbtso1PUCYKGkVtMKUUY8iEa"),
    totalFumbled: "$876,540",
    totalFumbledNum: 876540,
    worstFumbleToken: "NOBODY",
    worstFumbleDate: "Dec 1, 2025",
    worstFumbleAmount: "-$312,450",
    worstFumbleAmountNum: 312450,
    fumblesTracked: 6,
    rank: 8,
  },
  {
    name: "chester",
    walletAddress: "PMJA8UQDyWTFw2Smhyp9jGA6aTaP7jKHR7BPudrgyYN",
    imageUrl: getImageUrl("PMJA8UQDyWTFw2Smhyp9jGA6aTaP7jKHR7BPudrgyYN"),
    totalFumbled: "$765,890",
    totalFumbledNum: 765890,
    worstFumbleToken: "SAMO",
    worstFumbleDate: "Oct 25, 2025",
    worstFumbleAmount: "-$289,340",
    worstFumbleAmountNum: 289340,
    fumblesTracked: 7,
    rank: 9,
  },
  {
    name: "Cented",
    walletAddress: "CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o",
    imageUrl: getImageUrl("CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o"),
    totalFumbled: "$698,450",
    totalFumbledNum: 698450,
    worstFumbleToken: "WhiteWhale",
    worstFumbleDate: "Nov 5, 2025",
    worstFumbleAmount: "-$267,800",
    worstFumbleAmountNum: 267800,
    fumblesTracked: 5,
    rank: 10,
  },
  {
    name: "ram",
    walletAddress: "57rXqaQsvgyBKwebP2StfqQeCBjBS4jsrZFJN5aU2V9b",
    imageUrl: getImageUrl("57rXqaQsvgyBKwebP2StfqQeCBjBS4jsrZFJN5aU2V9b"),
    totalFumbled: "$645,780",
    totalFumbledNum: 645780,
    worstFumbleToken: "ORCA",
    worstFumbleDate: "Dec 12, 2025",
    worstFumbleAmount: "-$234,560",
    worstFumbleAmountNum: 234560,
    fumblesTracked: 4,
    rank: 11,
  },
  {
    name: "cap",
    walletAddress: "CAPn1yH4oSywsxGU456jfgTrSSUidf9jgeAnHceNUJdw",
    imageUrl: getImageUrl("CAPn1yH4oSywsxGU456jfgTrSSUidf9jgeAnHceNUJdw"),
    totalFumbled: "$598,230",
    totalFumbledNum: 598230,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 12,
  },
  {
    name: "aragon",
    walletAddress: "ARAGsRy1djAfRm2UvxCNB98Xrm7HU4b2pMzZZB6RjHpP",
    imageUrl: getImageUrl("ARAGsRy1djAfRm2UvxCNB98Xrm7HU4b2pMzZZB6RjHpP"),
    totalFumbled: "$567,340",
    totalFumbledNum: 567340,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 13,
  },
  {
    name: "Roody",
    walletAddress: "Roody1G4vFXxMJnMm8YNghsoNc7R8FtGq2A5v7MvYLT7",
    imageUrl: getImageUrl("Roody1G4vFXxMJnMm8YNghsoNc7R8FtGq2A5v7MvYLT7"),
    totalFumbled: "$534,560",
    totalFumbledNum: 534560,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 5,
    rank: 14,
  },
  {
    name: "DeFi Shark",
    walletAddress: "SHARKuQG9Hw6xmWYVJSvMnrHF7VB1W7xPi8vLHpVCCrR",
    imageUrl: getImageUrl("SHARKuQG9Hw6xmWYVJSvMnrHF7VB1W7xPi8vLHpVCCrR"),
    totalFumbled: "$512,890",
    totalFumbledNum: 512890,
    worstFumbleToken: "MNGO",
    worstFumbleDate: "Nov 18, 2025",
    worstFumbleAmount: "-$198,450",
    worstFumbleAmountNum: 198450,
    fumblesTracked: 6,
    rank: 15,
  },
  {
    name: "vibes",
    walletAddress: "VIBESxP9jwWkEJbXMxw1xU9KrqHEqJLoT2TQnNwDkFE4",
    imageUrl: getImageUrl("VIBESxP9jwWkEJbXMxw1xU9KrqHEqJLoT2TQnNwDkFE4"),
    totalFumbled: "$489,670",
    totalFumbledNum: 489670,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 16,
  },
  {
    name: "ponke",
    walletAddress: "PoNKEyoS7a5NqWBGZKdYvEMn3JBt3FKcJU8JNPJMwFC",
    imageUrl: getImageUrl("PoNKEyoS7a5NqWBGZKdYvEMn3JBt3FKcJU8JNPJMwFC"),
    totalFumbled: "$467,890",
    totalFumbledNum: 467890,
    worstFumbleToken: "STEP",
    worstFumbleDate: "Dec 3, 2025",
    worstFumbleAmount: "-$178,340",
    worstFumbleAmountNum: 178340,
    fumblesTracked: 5,
    rank: 17,
  },
  {
    name: "trader joe",
    walletAddress: "JOEcXPpbzQVxE7JRLwN4x9djYkhH9zKQFcwWEjh4pUeS",
    imageUrl: getImageUrl("JOEcXPpbzQVxE7JRLwN4x9djYkhH9zKQFcwWEjh4pUeS"),
    totalFumbled: "$445,120",
    totalFumbledNum: 445120,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 18,
  },
  {
    name: "memeking",
    walletAddress: "MEMEkingXLN4qwRvJNk7y3dH8QFVJ5rGtxpWdEL3Awcc",
    imageUrl: getImageUrl("MEMEkingXLN4qwRvJNk7y3dH8QFVJ5rGtxpWdEL3Awcc"),
    totalFumbled: "$423,560",
    totalFumbledNum: 423560,
    worstFumbleToken: "COPE",
    worstFumbleDate: "Nov 22, 2025",
    worstFumbleAmount: "-$156,780",
    worstFumbleAmountNum: 156780,
    fumblesTracked: 6,
    rank: 19,
  },
  {
    name: "solana god",
    walletAddress: "GoD1YJPmC7NN9kMg3sRQnPmGEa6pM9q8hFqBpfZQCGWC",
    imageUrl: getImageUrl("GoD1YJPmC7NN9kMg3sRQnPmGEa6pM9q8hFqBpfZQCGWC"),
    totalFumbled: "$398,780",
    totalFumbledNum: 398780,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 20,
  },
  {
    name: "whale watcher",
    walletAddress: "WhALExNfVL7qQvpn4MQo5kG8r5zNqKH3xJ9vYBChWzSx",
    imageUrl: getImageUrl("WhALExNfVL7qQvpn4MQo5kG8r5zNqKH3xJ9vYBChWzSx"),
    totalFumbled: "$378,450",
    totalFumbledNum: 378450,
    worstFumbleToken: "ATLAS",
    worstFumbleDate: "Oct 28, 2025",
    worstFumbleAmount: "-$145,670",
    worstFumbleAmountNum: 145670,
    fumblesTracked: 5,
    rank: 21,
  },
  {
    name: "alpha hunter",
    walletAddress: "ALPHAxWk5rY3nQpMJf7t8D9xVQGhZdRVcN3F7LqWdBtF",
    imageUrl: getImageUrl("ALPHAxWk5rY3nQpMJf7t8D9xVQGhZdRVcN3F7LqWdBtF"),
    totalFumbled: "$356,890",
    totalFumbledNum: 356890,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 22,
  },
  {
    name: "degen ape",
    walletAddress: "DeGenApe7nMXwY8kJ3F5qpLmVRHBN9gTx2DjWuNq8zVFC",
    imageUrl: getImageUrl("DeGenApe7nMXwY8kJ3F5qpLmVRHBN9gTx2DjWuNq8zVFC"),
    totalFumbled: "$334,560",
    totalFumbledNum: 334560,
    worstFumbleToken: "FIDA",
    worstFumbleDate: "Nov 15, 2025",
    worstFumbleAmount: "-$123,450",
    worstFumbleAmountNum: 123450,
    fumblesTracked: 4,
    rank: 23,
  },
  {
    name: "crypto nut",
    walletAddress: "NuTxB9rQpJf6kM7vN2DxLqWyZhP5cFgE8a3VdKm4wHJT",
    imageUrl: getImageUrl("NuTxB9rQpJf6kM7vN2DxLqWyZhP5cFgE8a3VdKm4wHJT"),
    totalFumbled: "$312,780",
    totalFumbledNum: 312780,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 5,
    rank: 24,
  },
  {
    name: "moon boy",
    walletAddress: "MooNxA3rQ5pJf8kM9vN4DxLqWzZhP7cFgG2a5VdKm6wK",
    imageUrl: getImageUrl("MooNxA3rQ5pJf8kM9vN4DxLqWzZhP7cFgG2a5VdKm6wK"),
    totalFumbled: "$298,340",
    totalFumbledNum: 298340,
    worstFumbleToken: "POLIS",
    worstFumbleDate: "Dec 10, 2025",
    worstFumbleAmount: "-$112,890",
    worstFumbleAmountNum: 112890,
    fumblesTracked: 4,
    rank: 25,
  },
  {
    name: "sol maxi",
    walletAddress: "SoLMaxiX7nMY3qRv8Nk5y2dH9QFVK6rGtxpXdFL4BwdD",
    imageUrl: getImageUrl("SoLMaxiX7nMY3qRv8Nk5y2dH9QFVK6rGtxpXdFL4BwdD"),
    totalFumbled: "$278,560",
    totalFumbledNum: 278560,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 26,
  },
  {
    name: "chart master",
    walletAddress: "ChArTxP8jwWkFJbYMxw2xU0KrqHFqKLoT3TRnNxEkGF5",
    imageUrl: getImageUrl("ChArTxP8jwWkFJbYMxw2xU0KrqHFqKLoT3TRnNxEkGF5"),
    totalFumbled: "$256,780",
    totalFumbledNum: 256780,
    worstFumbleToken: "MAPS",
    worstFumbleDate: "Nov 8, 2025",
    worstFumbleAmount: "-$98,450",
    worstFumbleAmountNum: 98450,
    fumblesTracked: 5,
    rank: 27,
  },
  {
    name: "nft flipper",
    walletAddress: "NFTflipR7qWkEKbXNxw3xU1LrqIGqLMoU4USoOyFlHG6",
    imageUrl: getImageUrl("NFTflipR7qWkEKbXNxw3xU1LrqIGqLMoU4USoOyFlHG6"),
    totalFumbled: "$234,890",
    totalFumbledNum: 234890,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 28,
  },
  {
    name: "yield farmer",
    walletAddress: "YiELDfarmS8rXkFLbYNxw4xU2MrqJHrMNoV5VTpPzGmH7",
    imageUrl: getImageUrl("YiELDfarmS8rXkFLbYNxw4xU2MrqJHrMNoV5VTpPzGmH7"),
    totalFumbled: "$212,340",
    totalFumbledNum: 212340,
    worstFumbleToken: "OXY",
    worstFumbleDate: "Oct 20, 2025",
    worstFumbleAmount: "-$87,560",
    worstFumbleAmountNum: 87560,
    fumblesTracked: 6,
    rank: 29,
  },
  {
    name: "airdrop hunter",
    walletAddress: "AirDrop9sYkGMcZOxw5xU3NrqKIsNPpW6WUpQAHnI8",
    imageUrl: getImageUrl("AirDrop9sYkGMcZOxw5xU3NrqKIsNPpW6WUpQAHnI8"),
    totalFumbled: "$198,670",
    totalFumbledNum: 198670,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 30,
  },
  {
    name: "liquidity king",
    walletAddress: "LiQkingAtZlHNdaPxw6xU4OrqLJtOQqX7XVrRBInJ9",
    imageUrl: getImageUrl("LiQkingAtZlHNdaPxw6xU4OrqLJtOQqX7XVrRBInJ9"),
    totalFumbled: "$187,450",
    totalFumbledNum: 187450,
    worstFumbleToken: "MEDIA",
    worstFumbleDate: "Nov 25, 2025",
    worstFumbleAmount: "-$76,340",
    worstFumbleAmountNum: 76340,
    fumblesTracked: 5,
    rank: 31,
  },
  {
    name: "perp trader",
    walletAddress: "PeRPtraderBuAmIOebQxw7xU5PrqMKuPRrY8YWsSCJoK",
    imageUrl: getImageUrl("PeRPtraderBuAmIOebQxw7xU5PrqMKuPRrY8YWsSCJoK"),
    totalFumbled: "$176,890",
    totalFumbledNum: 176890,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 32,
  },
  {
    name: "spot buyer",
    walletAddress: "SpoTbuyerCvBnJPfcRxw8xU6QrqNLvQSsZ9ZXtTDKpL",
    imageUrl: getImageUrl("SpoTbuyerCvBnJPfcRxw8xU6QrqNLvQSsZ9ZXtTDKpL"),
    totalFumbled: "$165,340",
    totalFumbledNum: 165340,
    worstFumbleToken: "ROPE",
    worstFumbleDate: "Dec 18, 2025",
    worstFumbleAmount: "-$67,890",
    worstFumbleAmountNum: 67890,
    fumblesTracked: 3,
    rank: 33,
  },
  {
    name: "swing trader",
    walletAddress: "SwInGtraderDwCoKQgdSxw9xU7SrqOMwRTtA0aYuUELqM",
    imageUrl: getImageUrl("SwInGtraderDwCoKQgdSxw9xU7SrqOMwRTtA0aYuUELqM"),
    totalFumbled: "$154,780",
    totalFumbledNum: 154780,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 5,
    rank: 34,
  },
  {
    name: "scalper",
    walletAddress: "ScAlPerExDpLRheTxwAxU8TrqPNxSUuB1bZvVFMnN",
    imageUrl: getImageUrl("ScAlPerExDpLRheTxwAxU8TrqPNxSUuB1bZvVFMnN"),
    totalFumbled: "$143,560",
    totalFumbledNum: 143560,
    worstFumbleToken: "SLIM",
    worstFumbleDate: "Nov 2, 2025",
    worstFumbleAmount: "-$56,780",
    worstFumbleAmountNum: 56780,
    fumblesTracked: 4,
    rank: 35,
  },
  {
    name: "hodler",
    walletAddress: "HoDLerFyEqMSifUxwBxU9UrqQOySVvC2cAaWwGNoO",
    imageUrl: getImageUrl("HoDLerFyEqMSifUxwBxU9UrqQOySVvC2cAaWwGNoO"),
    totalFumbled: "$132,890",
    totalFumbledNum: 132890,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 36,
  },
  {
    name: "diamond hands",
    walletAddress: "DiAmOnDhAnDs7GzFrNTjgVxwCxVAVrqRPzTWwD3dBbXxP",
    imageUrl: getImageUrl("DiAmOnDhAnDs7GzFrNTjgVxwCxVAVrqRPzTWwD3dBbXxP"),
    totalFumbled: "$123,450",
    totalFumbledNum: 123450,
    worstFumbleToken: "MER",
    worstFumbleDate: "Oct 15, 2025",
    worstFumbleAmount: "-$48,900",
    worstFumbleAmountNum: 48900,
    fumblesTracked: 6,
    rank: 37,
  },
  {
    name: "paper hands",
    walletAddress: "PaPeRhAnDsHz8AGs0UkhWxwDxWBWsrQAzUXxE4eCcYyQ",
    imageUrl: getImageUrl("PaPeRhAnDsHz8AGs0UkhWxwDxWBWsrQAzUXxE4eCcYyQ"),
    totalFumbled: "$112,780",
    totalFumbledNum: 112780,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 38,
  },
  {
    name: "rug pull vic",
    walletAddress: "RuGpuLLvicIy9BHt1VliXxwExXCXtrSBaVYyF5fDdZzR",
    imageUrl: getImageUrl("RuGpuLLvicIy9BHt1VliXxwExXCXtrSBaVYyF5fDdZzR"),
    totalFumbled: "$98,340",
    totalFumbledNum: 98340,
    worstFumbleToken: "COPE",
    worstFumbleDate: "Dec 22, 2025",
    worstFumbleAmount: "-$42,560",
    worstFumbleAmountNum: 42560,
    fumblesTracked: 5,
    rank: 39,
  },
  {
    name: "bot runner",
    walletAddress: "BoTrunNeRJz0CHu2WmjYxwFxYDYusTCbWZzG6gEeAaS",
    imageUrl: getImageUrl("BoTrunNeRJz0CHu2WmjYxwFxYDYusTCbWZzG6gEeAaS"),
    totalFumbled: "$87,560",
    totalFumbledNum: 87560,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 40,
  },
  {
    name: "sniping god",
    walletAddress: "SnIpInGgoDKa1DIv3XnkZxwGxZEZvuTDcXAxH7hFfBbT",
    imageUrl: getImageUrl("SnIpInGgoDKa1DIv3XnkZxwGxZEZvuTDcXAxH7hFfBbT"),
    totalFumbled: "$76,890",
    totalFumbledNum: 76890,
    worstFumbleToken: "ATLAS",
    worstFumbleDate: "Nov 30, 2025",
    worstFumbleAmount: "-$34,560",
    worstFumbleAmountNum: 34560,
    fumblesTracked: 4,
    rank: 41,
  },
  {
    name: "copy trader",
    walletAddress: "CoPyTrAdErLb2EJw4YolAxwHxAFAwvUEcYBxI8iGgCcU",
    imageUrl: getImageUrl("CoPyTrAdErLb2EJw4YolAxwHxAFAwvUEcYBxI8iGgCcU"),
    totalFumbled: "$67,340",
    totalFumbledNum: 67340,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 5,
    rank: 42,
  },
  {
    name: "fomo buyer",
    walletAddress: "FoMoBuYeRMc3FKx5ZpmBxwIxBGBxwVFfcZCxJ9jHhDdV",
    imageUrl: getImageUrl("FoMoBuYeRMc3FKx5ZpmBxwIxBGBxwVFfcZCxJ9jHhDdV"),
    totalFumbled: "$56,780",
    totalFumbledNum: 56780,
    worstFumbleToken: "STEP",
    worstFumbleDate: "Oct 8, 2025",
    worstFumbleAmount: "-$28,340",
    worstFumbleAmountNum: 28340,
    fumblesTracked: 3,
    rank: 43,
  },
  {
    name: "panic seller",
    walletAddress: "PaNiCsElLeRNd4GLy6AqnCxwJxCHCxwGGdaDxK0kIiEeW",
    imageUrl: getImageUrl("PaNiCsElLeRNd4GLy6AqnCxwJxCHCxwGGdaDxK0kIiEeW"),
    totalFumbled: "$48,560",
    totalFumbledNum: 48560,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 44,
  },
  {
    name: "revenge trader",
    walletAddress: "ReVeNgEtRaDeROe5HMz7BroExwKxDIDxwHHebExL1lJjFfX",
    imageUrl: getImageUrl("ReVeNgEtRaDeROe5HMz7BroExwKxDIDxwHHebExL1lJjFfX"),
    totalFumbled: "$42,340",
    totalFumbledNum: 42340,
    worstFumbleToken: "SAMO",
    worstFumbleDate: "Dec 5, 2025",
    worstFumbleAmount: "-$21,780",
    worstFumbleAmountNum: 21780,
    fumblesTracked: 5,
    rank: 45,
  },
  {
    name: "whale sniffer",
    walletAddress: "WhAlEsNiFfErPf6INa8CspFxwLxEJExwIIfcFxM2mKkGgY",
    imageUrl: getImageUrl("WhAlEsNiFfErPf6INa8CspFxwLxEJExwIIfcFxM2mKkGgY"),
    totalFumbled: "$38,890",
    totalFumbledNum: 38890,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 46,
  },
  {
    name: "early adopter",
    walletAddress: "EaRlYaDoPtErQg7JOb9DtqGxwMxFKFxwJJgdGxN3nLlHhZ",
    imageUrl: getImageUrl("EaRlYaDoPtErQg7JOb9DtqGxwMxFKFxwJJgdGxN3nLlHhZ"),
    totalFumbled: "$34,560",
    totalFumbledNum: 34560,
    worstFumbleToken: "RAY",
    worstFumbleDate: "Nov 12, 2025",
    worstFumbleAmount: "-$18,450",
    worstFumbleAmountNum: 18450,
    fumblesTracked: 4,
    rank: 47,
  },
  {
    name: "late ape",
    walletAddress: "LaTe4pERh8KPcAEurHxwNxGLGxwKKheHxO4oMmIiA",
    imageUrl: getImageUrl("LaTe4pERh8KPcAEurHxwNxGLGxwKKheHxO4oMmIiA"),
    totalFumbled: "$31,230",
    totalFumbledNum: 31230,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 5,
    rank: 48,
  },
  {
    name: "top buyer",
    walletAddress: "ToPbUyErSi9LQdBFvsIxwOxHMHxwLLifIxP5pNnJjB",
    imageUrl: getImageUrl("ToPbUyErSi9LQdBFvsIxwOxHMHxwLLifIxP5pNnJjB"),
    totalFumbled: "$28,670",
    totalFumbledNum: 28670,
    worstFumbleToken: "ORCA",
    worstFumbleDate: "Oct 22, 2025",
    worstFumbleAmount: "-$15,340",
    worstFumbleAmountNum: 15340,
    fumblesTracked: 3,
    rank: 49,
  },
  {
    name: "bottom seller",
    walletAddress: "BoTtOmSeLlErTj0MReCGwtJxwPxINIxwMMjgJxQ6qOoKkC",
    imageUrl: getImageUrl("BoTtOmSeLlErTj0MReCGwtJxwPxINIxwMMjgJxQ6qOoKkC"),
    totalFumbled: "$26,450",
    totalFumbledNum: 26450,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 50,
  },
  {
    name: "over leveraged",
    walletAddress: "OvErLeVeRaGeDUk1NSfDHxuKxwQxJOJxwNNkhKxR7rPpLlD",
    imageUrl: getImageUrl("OvErLeVeRaGeDUk1NSfDHxuKxwQxJOJxwNNkhKxR7rPpLlD"),
    totalFumbled: "$24,780",
    totalFumbledNum: 24780,
    worstFumbleToken: "JTO",
    worstFumbleDate: "Dec 15, 2025",
    worstFumbleAmount: "-$12,890",
    worstFumbleAmountNum: 12890,
    fumblesTracked: 5,
    rank: 51,
  },
  {
    name: "margin called",
    walletAddress: "MaRgInCaLlEdVl2OTgEIyvLxwRxKPKxwOOliLxS8sQqMmE",
    imageUrl: getImageUrl("MaRgInCaLlEdVl2OTgEIyvLxwRxKPKxwOOliLxS8sQqMmE"),
    totalFumbled: "$23,120",
    totalFumbledNum: 23120,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 52,
  },
  {
    name: "stop loss hit",
    walletAddress: "StOpLoSsHiTWm3PUhFJzwMxwSxLQLxwPPmjMxT9tRrNnF",
    imageUrl: getImageUrl("StOpLoSsHiTWm3PUhFJzwMxwSxLQLxwPPmjMxT9tRrNnF"),
    totalFumbled: "$21,560",
    totalFumbledNum: 21560,
    worstFumbleToken: "WIF",
    worstFumbleDate: "Nov 28, 2025",
    worstFumbleAmount: "-$10,780",
    worstFumbleAmountNum: 10780,
    fumblesTracked: 4,
    rank: 53,
  },
  {
    name: "take profit miss",
    walletAddress: "TaKePrOfItMiSsXn4QViGKawNxwTxMRMxwQQnkNxU0uSsOoG",
    imageUrl: getImageUrl("TaKePrOfItMiSsXn4QViGKawNxwTxMRMxwQQnkNxU0uSsOoG"),
    totalFumbled: "$20,340",
    totalFumbledNum: 20340,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 5,
    rank: 54,
  },
  {
    name: "greedy gamer",
    walletAddress: "GrEeDyGaMeRYo5RWjHLbxOxwUxNSNxwRRolOxV1vTtPpH",
    imageUrl: getImageUrl("GrEeDyGaMeRYo5RWjHLbxOxwUxNSNxwRRolOxV1vTtPpH"),
    totalFumbled: "$19,780",
    totalFumbledNum: 19780,
    worstFumbleToken: "BONK",
    worstFumbleDate: "Oct 5, 2025",
    worstFumbleAmount: "-$9,890",
    worstFumbleAmountNum: 9890,
    fumblesTracked: 3,
    rank: 55,
  },
  {
    name: "impatient trader",
    walletAddress: "ImPaTiEnTtRaDeRZp6SXkIMcyPxwVxOTOxwSSpmPxW2wUuQqI",
    imageUrl: getImageUrl("ImPaTiEnTtRaDeRZp6SXkIMcyPxwVxOTOxwSSpmPxW2wUuQqI"),
    totalFumbled: "$18,450",
    totalFumbledNum: 18450,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 56,
  },
  {
    name: "emotional trader",
    walletAddress: "EmOtIoNaLtRaDeRAq7TYlJNdzQxwWxPUPxwTTqnQxX3xVvRrJ",
    imageUrl: getImageUrl("EmOtIoNaLtRaDeRAq7TYlJNdzQxwWxPUPxwTTqnQxX3xVvRrJ"),
    totalFumbled: "$17,560",
    totalFumbledNum: 17560,
    worstFumbleToken: "PYTH",
    worstFumbleDate: "Dec 8, 2025",
    worstFumbleAmount: "-$8,780",
    worstFumbleAmountNum: 8780,
    fumblesTracked: 5,
    rank: 57,
  },
  {
    name: "overconfident",
    walletAddress: "OvErCoNfIdEnTBr8UZmKOeaRxwXxQVQxwUUroRxY4yWwSsK",
    imageUrl: getImageUrl("OvErCoNfIdEnTBr8UZmKOeaRxwXxQVQxwUUroRxY4yWwSsK"),
    totalFumbled: "$16,890",
    totalFumbledNum: 16890,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 58,
  },
  {
    name: "undercapitalized",
    walletAddress: "UnDeRcApItAlIzEdCs9VAnLPfbSxwYxRWRxwVVspSxZ5zXxTtL",
    imageUrl: getImageUrl("UnDeRcApItAlIzEdCs9VAnLPfbSxwYxRWRxwVVspSxZ5zXxTtL"),
    totalFumbled: "$16,230",
    totalFumbledNum: 16230,
    worstFumbleToken: "MEME",
    worstFumbleDate: "Nov 18, 2025",
    worstFumbleAmount: "-$8,120",
    worstFumbleAmountNum: 8120,
    fumblesTracked: 4,
    rank: 59,
  },
  {
    name: "no plan",
    walletAddress: "NoPlAnDt0WBoMQgcTxwZxSXSxwWWtqTxA6aYyUuM",
    imageUrl: getImageUrl("NoPlAnDt0WBoMQgcTxwZxSXSxwWWtqTxA6aYyUuM"),
    totalFumbled: "$15,670",
    totalFumbledNum: 15670,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 5,
    rank: 60,
  },
  {
    name: "risk ignorer",
    walletAddress: "RiSkIgNoReREu1XCpNRhdUxwAxTYTxwXXurUxB7bZzVvN",
    imageUrl: getImageUrl("RiSkIgNoReREu1XCpNRhdUxwAxTYTxwXXurUxB7bZzVvN"),
    totalFumbled: "$15,120",
    totalFumbledNum: 15120,
    worstFumbleToken: "FIDA",
    worstFumbleDate: "Oct 12, 2025",
    worstFumbleAmount: "-$7,560",
    worstFumbleAmountNum: 7560,
    fumblesTracked: 3,
    rank: 61,
  },
  {
    name: "all in andy",
    walletAddress: "AlLiNaNdYFv2YDqOSSieVxwBxUZUxwYYvsVxC8cAaWwO",
    imageUrl: getImageUrl("AlLiNaNdYFv2YDqOSSieVxwBxUZUxwYYvsVxC8cAaWwO"),
    totalFumbled: "$14,670",
    totalFumbledNum: 14670,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 62,
  },
  {
    name: "portfolio rekt",
    walletAddress: "PoRtFoLiOrEkTGw3ZErPTTjfWxwCxVAVxwZZwtWxD9dBbXxP",
    imageUrl: getImageUrl("PoRtFoLiOrEkTGw3ZErPTTjfWxwCxVAVxwZZwtWxD9dBbXxP"),
    totalFumbled: "$14,230",
    totalFumbledNum: 14230,
    worstFumbleToken: "MNGO",
    worstFumbleDate: "Dec 20, 2025",
    worstFumbleAmount: "-$7,120",
    worstFumbleAmountNum: 7120,
    fumblesTracked: 5,
    rank: 63,
  },
  {
    name: "bag holder",
    walletAddress: "BaGhOlDeRHx4AFsQUUkgXxwDxWBWxwAAxuXxE0eCcYyQ",
    imageUrl: getImageUrl("BaGhOlDeRHx4AFsQUUkgXxwDxWBWxwAAxuXxE0eCcYyQ"),
    totalFumbled: "$13,890",
    totalFumbledNum: 13890,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 64,
  },
  {
    name: "exit liquidity",
    walletAddress: "ExItLiQuIdItYIy5BGtRVVlhYxwExXCXxwBByvYxF1fDdZzR",
    imageUrl: getImageUrl("ExItLiQuIdItYIy5BGtRVVlhYxwExXCXxwBByvYxF1fDdZzR"),
    totalFumbled: "$13,560",
    totalFumbledNum: 13560,
    worstFumbleToken: "POLIS",
    worstFumbleDate: "Nov 5, 2025",
    worstFumbleAmount: "-$6,780",
    worstFumbleAmountNum: 6780,
    fumblesTracked: 4,
    rank: 65,
  },
  {
    name: "normie trader",
    walletAddress: "NoRmIeTraDeRJz6CHuWWmiZxwFxYDYxwCCzwZxG2gEeAaS",
    imageUrl: getImageUrl("NoRmIeTraDeRJz6CHuWWmiZxwFxYDYxwCCzwZxG2gEeAaS"),
    totalFumbled: "$13,230",
    totalFumbledNum: 13230,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 5,
    rank: 66,
  },
  {
    name: "new to crypto",
    walletAddress: "NeWtOcRyPtOKa7DIvXXnkAaAxwGxZEZxwDDaxAaH3hFfBbT",
    imageUrl: getImageUrl("NeWtOcRyPtOKa7DIvXXnkAaAxwGxZEZxwDDaxAaH3hFfBbT"),
    totalFumbled: "$12,890",
    totalFumbledNum: 12890,
    worstFumbleToken: "STEP",
    worstFumbleDate: "Oct 28, 2025",
    worstFumbleAmount: "-$6,450",
    worstFumbleAmountNum: 6450,
    fumblesTracked: 3,
    rank: 67,
  },
  {
    name: "influencer vic",
    walletAddress: "InFlUeNcErViCLb8EJwYYolBbBxwHxAFAxwEEbxBxI4iGgCcU",
    imageUrl: getImageUrl("InFlUeNcErViCLb8EJwYYolBbBxwHxAFAxwEEbxBxI4iGgCcU"),
    totalFumbled: "$12,560",
    totalFumbledNum: 12560,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 68,
  },
  {
    name: "youtube watcher",
    walletAddress: "YoUtUbEwAtChErMc9FKxZZpmCcCxwIxBGBxwFFcxCxJ5jHhDdV",
    imageUrl: getImageUrl("YoUtUbEwAtChErMc9FKxZZpmCcCxwIxBGBxwFFcxCxJ5jHhDdV"),
    totalFumbled: "$12,230",
    totalFumbledNum: 12230,
    worstFumbleToken: "ATLAS",
    worstFumbleDate: "Dec 12, 2025",
    worstFumbleAmount: "-$6,120",
    worstFumbleAmountNum: 6120,
    fumblesTracked: 5,
    rank: 69,
  },
  {
    name: "twitter alpha",
    walletAddress: "TwItTeRaLpHaNd0GLyAAqnDdDxwJxCHCxwGGdaDxK6kIiEeW",
    imageUrl: getImageUrl("TwItTeRaLpHaNd0GLyAAqnDdDxwJxCHCxwGGdaDxK6kIiEeW"),
    totalFumbled: "$11,890",
    totalFumbledNum: 11890,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 70,
  },
  {
    name: "discord mod",
    walletAddress: "DiScOrDmOdOe1HMzBBroEeExwKxDIDxwHHebExL7lJjFfX",
    imageUrl: getImageUrl("DiScOrDmOdOe1HMzBBroEeExwKxDIDxwHHebExL7lJjFfX"),
    totalFumbled: "$11,560",
    totalFumbledNum: 11560,
    worstFumbleToken: "COPE",
    worstFumbleDate: "Nov 22, 2025",
    worstFumbleAmount: "-$5,780",
    worstFumbleAmountNum: 5780,
    fumblesTracked: 4,
    rank: 71,
  },
  {
    name: "telegram alpha",
    walletAddress: "TeLgRaMaLpHaPf2INaCCspFfFxwLxEJExwIIfcFxM8mKkGgY",
    imageUrl: getImageUrl("TeLgRaMaLpHaPf2INaCCspFfFxwLxEJExwIIfcFxM8mKkGgY"),
    totalFumbled: "$11,230",
    totalFumbledNum: 11230,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 5,
    rank: 72,
  },
  {
    name: "signal follower",
    walletAddress: "SiGnAlFoLlOwErQg3JObDDtqGgGxwMxFKFxwJJgdGxN9nLlHhZ",
    imageUrl: getImageUrl("SiGnAlFoLlOwErQg3JObDDtqGgGxwMxFKFxwJJgdGxN9nLlHhZ"),
    totalFumbled: "$10,890",
    totalFumbledNum: 10890,
    worstFumbleToken: "SAMO",
    worstFumbleDate: "Oct 15, 2025",
    worstFumbleAmount: "-$5,450",
    worstFumbleAmountNum: 5450,
    fumblesTracked: 3,
    rank: 73,
  },
  {
    name: "pump chaser",
    walletAddress: "PuMpChAsErRh4KPcEEurHhHxwNxGLGxwKKheHxO0oMmIiA",
    imageUrl: getImageUrl("PuMpChAsErRh4KPcEEurHhHxwNxGLGxwKKheHxO0oMmIiA"),
    totalFumbled: "$10,560",
    totalFumbledNum: 10560,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 74,
  },
  {
    name: "dump victim",
    walletAddress: "DuMpViCtImSi5LQdFFvsIiIxwOxHMHxwLLifIxP1pNnJjB",
    imageUrl: getImageUrl("DuMpViCtImSi5LQdFFvsIiIxwOxHMHxwLLifIxP1pNnJjB"),
    totalFumbled: "$10,230",
    totalFumbledNum: 10230,
    worstFumbleToken: "OXY",
    worstFumbleDate: "Dec 25, 2025",
    worstFumbleAmount: "-$5,120",
    worstFumbleAmountNum: 5120,
    fumblesTracked: 5,
    rank: 75,
  },
  {
    name: "pump fun user",
    walletAddress: "PuMpFuNuSeRTj6MReCGwtJjJxwPxINIxwMMjgJxQ2qOoKkC",
    imageUrl: getImageUrl("PuMpFuNuSeRTj6MReCGwtJjJxwPxINIxwMMjgJxQ2qOoKkC"),
    totalFumbled: "$9,890",
    totalFumbledNum: 9890,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 3,
    rank: 76,
  },
  {
    name: "meme buyer",
    walletAddress: "MeMeBuYeRUk7NSfDHxuKkKxwQxJOJxwNNkhKxR3rPpLlD",
    imageUrl: getImageUrl("MeMeBuYeRUk7NSfDHxuKkKxwQxJOJxwNNkhKxR3rPpLlD"),
    totalFumbled: "$9,560",
    totalFumbledNum: 9560,
    worstFumbleToken: "MEDIA",
    worstFumbleDate: "Nov 8, 2025",
    worstFumbleAmount: "-$4,780",
    worstFumbleAmountNum: 4780,
    fumblesTracked: 4,
    rank: 77,
  },
  {
    name: "shitcoin lover",
    walletAddress: "ShItCoInLoVeRVl8OTgEIyvLlLxwRxKPKxwOOliLxS4sQqMmE",
    imageUrl: getImageUrl("ShItCoInLoVeRVl8OTgEIyvLlLxwRxKPKxwOOliLxS4sQqMmE"),
    totalFumbled: "$9,230",
    totalFumbledNum: 9230,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 5,
    rank: 78,
  },
  {
    name: "hopium addict",
    walletAddress: "HoPiUmAdDiCtWm9PUhFJzwMmMxwSxLQLxwPPmjMxT5tRrNnF",
    imageUrl: getImageUrl("HoPiUmAdDiCtWm9PUhFJzwMmMxwSxLQLxwPPmjMxT5tRrNnF"),
    totalFumbled: "$8,890",
    totalFumbledNum: 8890,
    worstFumbleToken: "MAPS",
    worstFumbleDate: "Oct 2, 2025",
    worstFumbleAmount: "-$4,450",
    worstFumbleAmountNum: 4450,
    fumblesTracked: 3,
    rank: 79,
  },
  {
    name: "copium dealer",
    walletAddress: "CoPiUmDeAlErXn0QViGKawNnNxwTxMRMxwQQnkNxU6uSsOoG",
    imageUrl: getImageUrl("CoPiUmDeAlErXn0QViGKawNnNxwTxMRMxwQQnkNxU6uSsOoG"),
    totalFumbled: "$8,560",
    totalFumbledNum: 8560,
    worstFumbleToken: "Data loading",
    worstFumbleDate: "Data loading",
    worstFumbleAmount: "Calculating...",
    worstFumbleAmountNum: 0,
    fumblesTracked: 4,
    rank: 80,
  },
];

export const TOTAL_KOLS_COUNT = kolsDisplayData.length;
